Restore the lib

diff --git a/.github/actions/pulumi-deploy/action.yml b/.github/actions/pulumi-deploy/action.yml
--- a/.github/actions/pulumi-deploy/action.yml
+++ b/.github/actions/pulumi-deploy/action.yml
@@ -36,74 +36,83 @@ inputs:
     description: Whether the stack uses the CRDs library.
     required: false
     default: 'false'
+  uses-lib:
+    description: Whether the stack uses the shared library.
+    required: false
+    default: 'true'
   pre-deploy-script:
     description: The path to a script to run before deploying.
     required: false
 runs:
   using: composite
   steps:
-    - name: Validate inputs
-      shell: bash
-      run: |
-        case '${{ inputs.kind }}' in
-          apps | clusters | infra);;
-          *) echo "Invalid kind" && exit 1;;
-        esac
+  - name: Validate inputs
+    shell: bash
+    run: |
+      case '${{ inputs.kind }}' in
+        apps | clusters | infra);;
+        *) echo "Invalid kind" && exit 1;;
+      esac
 
-        case "${{ inputs.op }}" in
-          preview | up);;
-          *) echo "Invalid operation" && exit 1;;
-        esac
+      case "${{ inputs.op }}" in
+        preview | up);;
+        *) echo "Invalid operation" && exit 1;;
+      esac
 
-    - id: setup
-      uses: ./.github/actions/setup-config
-      if: inputs.kind == 'apps'
-      with:
-        cluster: ${{ inputs.stack }}
+  - id: setup
+    uses: ./.github/actions/setup-config
+    if: inputs.kind == 'apps'
+    with:
+      cluster: ${{ inputs.stack }}
 
-    - shell: bash
-      run: npm ci
-      working-directory: ${{ inputs.kind }}/${{ inputs.project }}
+  - shell: bash
+    run: npm ci
+    working-directory: ${{ inputs.kind }}/${{ inputs.project }}
 
-    - if: inputs.uses-crds == 'true'
-      shell: bash
-      run: npm ci
-      working-directory: lib/crds
+  - if: inputs.uses-crds == 'true'
+    shell: bash
+    run: npm ci
+    working-directory: lib/crds
 
-    - shell: bash
-      run: |
-        if [ $(ls -1 Chart.{yml,yaml} 2>/dev/null | wc -l) -gt 0 ]; then
-          helm dependency update
-        fi
-      working-directory: ${{ inputs.kind }}/${{ inputs.project }}
+  - if: inputs.uses-lib == 'true'
+    shell: bash
+    run: npm ci
+    working-directory: lib/nodejs
 
-    - if: inputs.pre-deploy-script != 'true'
-      shell: bash
-      run: ${{ inputs.pre-deploy-script }}
-      working-directory: ${{ inputs.kind }}/${{ inputs.project }}
+  - shell: bash
+    run: |
+      if [ $(ls -1 Chart.{yml,yaml} 2>/dev/null | wc -l) -gt 0 ]; then
+        helm dependency update
+      fi
+    working-directory: ${{ inputs.kind }}/${{ inputs.project }}
 
-    - name: Pulumi ${{ inputs.op }}
-      uses: pulumi/actions@v4
-      with:
-        stack-name: UnstoppableMango/thecluster-${{ inputs.project }}/${{ inputs.stack }}
-        command: ${{ inputs.op }}
-        work-dir: ${{ inputs.kind }}/${{ inputs.project }}
-        comment-on-pr: true
-        refresh: true
-      env:
-        KUBECONFIG: ${{ steps.setup.outputs.kubeconfig }}
+  - if: inputs.pre-deploy-script != 'true'
+    shell: bash
+    run: ${{ inputs.pre-deploy-script }}
+    working-directory: ${{ inputs.kind }}/${{ inputs.project }}
 
-    - name: Validate
-      if: inputs.op == 'up'
-      shell: bash
-      run: |
-        if [ -f "$SCRIPT" ]; then
-          $SCRIPT
-        else
-          echo "No verification script found at $SCRIPT"
-        fi
-      env:
-        KUBECONFIG: ${{ steps.setup.outputs.kubeconfig }}
-        TALOSCONFIG: ${{ steps.setup.outputs.talosconfig }}
-        SCRIPT: ${{ inputs.verify-script }}
-      working-directory: ${{ inputs.kind }}/${{ inputs.project }}
+  - name: Pulumi ${{ inputs.op }}
+    uses: pulumi/actions@v4
+    with:
+      stack-name: UnstoppableMango/thecluster-${{ inputs.project }}/${{ inputs.stack }}
+      command: ${{ inputs.op }}
+      work-dir: ${{ inputs.kind }}/${{ inputs.project }}
+      comment-on-pr: true
+      refresh: true
+    env:
+      KUBECONFIG: ${{ steps.setup.outputs.kubeconfig }}
+
+  - name: Validate
+    if: inputs.op == 'up'
+    shell: bash
+    run: |
+      if [ -f "$SCRIPT" ]; then
+        $SCRIPT
+      else
+        echo "No verification script found at $SCRIPT"
+      fi
+    env:
+      KUBECONFIG: ${{ steps.setup.outputs.kubeconfig }}
+      TALOSCONFIG: ${{ steps.setup.outputs.talosconfig }}
+      SCRIPT: ${{ inputs.verify-script }}
+    working-directory: ${{ inputs.kind }}/${{ inputs.project }}
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,6 +37,11 @@ on:
         type: boolean
         required: false
         default: false
+      uses-lib:
+        description: Whether the stack uses the shared library.
+        type: boolean
+        required: false
+        default: true
       pre-deploy-script:
         description: The path to a script to run before deploying the stack.
         type: string
@@ -55,35 +60,36 @@ jobs:
       run:
         working-directory: ${{ env.PROJECT_DIR }}
     steps:
-      - uses: actions/checkout@v4
+    - uses: actions/checkout@v4
 
-      - name: Validate inputs
-        run: |
-          case "${{ inputs.kind }}" in
-            apps | clusters | infra);;
-            *) echo "Invalid kind" && exit 1;;
-          esac
+    - name: Validate inputs
+      run: |
+        case "${{ inputs.kind }}" in
+          apps | clusters | infra);;
+          *) echo "Invalid kind" && exit 1;;
+        esac
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: .nvmrc
-          cache: npm
-          cache-dependency-path: |
-            ${{ env.PROJECT_DIR }}/package-lock.json
-            lib/crds/package-lock.json
+    - uses: actions/setup-node@v4
+      with:
+        node-version-file: .nvmrc
+        cache: npm
+        cache-dependency-path: |
+          ${{ env.PROJECT_DIR }}/package-lock.json
+          lib/crds/package-lock.json
 
-      - uses: ./.github/actions/setup-tools
-        with:
-          all: true
-          token: ${{ secrets.GITHUB_TOKEN }}
+    - uses: ./.github/actions/setup-tools
+      with:
+        all: true
+        token: ${{ secrets.GITHUB_TOKEN }}
 
-      - uses: ./.github/actions/pulumi-deploy
-        with:
-          project: ${{ inputs.project }}
-          stack: ${{ inputs.stack }}
-          kind: ${{ inputs.kind }}
-          op: ${{ env.OPERATION }}
-          verify: ${{ inputs.verify }}
-          verify-script: ${{ inputs.verify-script }}
-          uses-crds: ${{ inputs.uses-crds }}
-          pre-deploy-script: ${{ inputs.pre-deploy-script }}
+    - uses: ./.github/actions/pulumi-deploy
+      with:
+        project: ${{ inputs.project }}
+        stack: ${{ inputs.stack }}
+        kind: ${{ inputs.kind }}
+        op: ${{ env.OPERATION }}
+        verify: ${{ inputs.verify }}
+        verify-script: ${{ inputs.verify-script }}
+        uses-crds: ${{ inputs.uses-crds }}
+        uses-lib: ${{ inputs.uses-lib }}
+        pre-deploy-script: ${{ inputs.pre-deploy-script }}
